import type { AppData, EventData, DepartmentData } from "./types";

export const appData: AppData[] = [
  {
    id: "iwallet",
    name: "Iwallet",
    icon: "ph-duotone ph-wallet",
    imageSrc: "/iwallet.png",
    cardClass: "ac-1",
    logoColor: "#ea580c",
    modalRgb: "249,115,22",
    modalLogoBg: "linear-gradient(135deg, #fed7aa, #fdba74)",
    modalLogoColor: "#ea580c",
    desc: "Digital wallet for secure transactions and financial management.",
    longDesc:
      "Iwallet is Inspire Group's proprietary digital payment platform, enabling secure peer-to-peer transactions, expense management, and multi-currency wallet operations across all departments.",
    features: [
      { icon: "ph-duotone ph-credit-card", text: "Digital payments & transfers" },
      { icon: "ph-duotone ph-chart-pie", text: "Expense tracking & reports" },
      { icon: "ph-duotone ph-coins", text: "Multi-currency wallets" },
      { icon: "ph-duotone ph-calculator", text: "Budget management tools" },
      { icon: "ph-duotone ph-bell-ringing", text: "Real-time transaction alerts" },
      { icon: "ph-duotone ph-shield-check", text: "Secure two-factor auth" },
    ],
    videos: [
      { title: "Getting Started with Iwallet", desc: "Complete onboarding walkthrough", gradient: "linear-gradient(135deg, #f97316, #c2410c)" },
      { title: "Advanced Payment Features", desc: "Multi-currency and batch payments", gradient: "linear-gradient(135deg, #fb923c, #ea580c)" },
    ],
  },
  {
    id: "loopwork",
    name: "Loopwork",
    icon: "ph-duotone ph-arrows-clockwise",
    imageSrc: "/loopwork.png",
    cardClass: "ac-2",
    logoColor: "#2563eb",
    modalRgb: "37,99,235",
    modalLogoBg: "linear-gradient(135deg, #bfdbfe, #93c5fd)",
    modalLogoColor: "#2563eb",
    desc: "Workflow management and intelligent task automation platform.",
    longDesc:
      "Loopwork streamlines project management with smart Kanban boards, automated task routing, time tracking, and real-time team collaboration designed for enterprise efficiency.",
    features: [
      { icon: "ph-duotone ph-kanban", text: "Kanban & sprint boards" },
      { icon: "ph-duotone ph-lightning", text: "Automated workflows" },
      { icon: "ph-duotone ph-timer", text: "Time tracking & logs" },
      { icon: "ph-duotone ph-chats-circle", text: "Team collaboration chat" },
      { icon: "ph-duotone ph-users", text: "Resource management" },
      { icon: "ph-duotone ph-chart-line-up", text: "Performance analytics" },
    ],
    videos: [
      { title: "Board Setup & Configuration", desc: "Create your first project board", gradient: "linear-gradient(135deg, #3b82f6, #1d4ed8)" },
      { title: "Automation Rules Engine", desc: "Build custom workflow triggers", gradient: "linear-gradient(135deg, #60a5fa, #2563eb)" },
    ],
  },
  {
    id: "hrx",
    name: "HRX",
    icon: "ph-duotone ph-identification-badge",
    imageSrc: "/hrx.png",
    cardClass: "ac-3",
    logoColor: "#d97706",
    modalRgb: "217,119,6",
    modalLogoBg: "linear-gradient(135deg, #fef3c7, #fde68a)",
    modalLogoColor: "#d97706",
    desc: "Human resources platform for attendance, leave, and payroll.",
    longDesc:
      "HRX is the all-in-one human resources management system handling attendance tracking, leave applications, payroll processing, employee directory, and performance review cycles.",
    features: [
      { icon: "ph-duotone ph-fingerprint", text: "Attendance & time logs" },
      { icon: "ph-duotone ph-calendar-blank", text: "Leave management portal" },
      { icon: "ph-duotone ph-money", text: "Payroll processing" },
      { icon: "ph-duotone ph-address-book", text: "Employee directory" },
      { icon: "ph-duotone ph-star", text: "Performance reviews" },
      { icon: "ph-duotone ph-user-plus", text: "Onboarding workflows" },
    ],
    videos: [
      { title: "Filing Leave Requests", desc: "Step-by-step leave application", gradient: "linear-gradient(135deg, #fbbf24, #b45309)" },
      { title: "Payroll Dashboard Tour", desc: "Navigate payslips and deductions", gradient: "linear-gradient(135deg, #f59e0b, #d97706)" },
    ],
  },
  {
    id: "cms",
    name: "CMS",
    icon: "ph-duotone ph-browser",
    imageSrc: "/cms.png",
    cardClass: "ac-4",
    logoColor: "#9333ea",
    modalRgb: "168,85,247",
    modalLogoBg: "linear-gradient(135deg, #e9d5ff, #d8b4fe)",
    modalLogoColor: "#9333ea",
    desc: "Visual web builder for designing and publishing pages — like Figma, but live.",
    longDesc:
      "Our CMS is a visual web builder that lets teams design, prototype, and publish pages without writing code. Think Figma-style drag-and-drop editing with live preview, reusable components, and one-click publishing across all company channels.",
    features: [
      { icon: "ph-duotone ph-layout", text: "Page builder & editor" },
      { icon: "ph-duotone ph-image", text: "Asset library management" },
      { icon: "ph-duotone ph-git-branch", text: "Version control & history" },
      { icon: "ph-duotone ph-globe", text: "Multi-site management" },
      { icon: "ph-duotone ph-magnifying-glass", text: "SEO optimization tools" },
      { icon: "ph-duotone ph-clock-countdown", text: "Scheduled publishing" },
    ],
    videos: [
      { title: "Creating Your First Page", desc: "Drag-and-drop page builder basics", gradient: "linear-gradient(135deg, #a855f7, #7e22ce)" },
      { title: "Asset Management Guide", desc: "Upload, organize, and optimize media", gradient: "linear-gradient(135deg, #c084fc, #9333ea)" },
    ],
  },
];

export const eventData: EventData[] = [
  {
    id: "event1",
    icon: "ph-duotone ph-calendar-star",
    tagIcon: "ph-bold ph-star",
    tagLabel: "Event",
    slideClass: "cs-1",
    title: "Annual Summit 2026",
    shortDesc:
      "Join us for keynotes, workshops, and team-building across three full days.",
    fullDesc:
      "The Annual Inspire Summit brings together all departments for a three-day event featuring keynote speeches from leadership, interactive workshops on emerging technologies, cross-department collaboration sessions, and team-building activities designed to strengthen our organizational culture.",
    date: "March 28, 2026",
    location: "Grand Plaza",
    posterGradient: "linear-gradient(135deg, var(--inspire-blue), #1e3a8a)",
  },
  {
    id: "event2",
    icon: "ph-duotone ph-laptop",
    tagIcon: "ph-bold ph-megaphone",
    tagLabel: "Update",
    slideClass: "cs-2",
    title: "Hybrid Work Policy",
    shortDesc:
      "We're officially rolling out a flexible hybrid model. Review the new guidelines.",
    fullDesc:
      "Beginning April 2026, Inspire Group will officially adopt a hybrid work model. Employees may work remotely up to 3 days per week with manager approval. Updated guidelines covering equipment allowances, communication protocols, and performance expectations are now available in the HR portal.",
    date: "March 22, 2026",
    location: "All Departments",
    posterGradient: "linear-gradient(135deg, var(--inspire-purple), #4c1d95)",
  },
  {
    id: "event3",
    icon: "ph-duotone ph-trophy",
    tagIcon: "ph-bold ph-award",
    tagLabel: "Award",
    slideClass: "cs-3",
    title: "Employee Spotlight",
    shortDesc:
      "Congratulations to the IT Department for the successful launch of Iwallet v3.",
    fullDesc:
      "The IT Department has been recognized for the successful launch of Iwallet v3, our next-generation digital payment platform. The team completed the project 2 weeks ahead of schedule while maintaining zero critical bugs in production. Congratulations to the entire team!",
    date: "March 18, 2026",
    location: "IT Department",
    posterGradient: "linear-gradient(135deg, var(--inspire-orange), #7c2d12)",
  },
  {
    id: "event4",
    icon: "ph-duotone ph-warning-circle",
    tagIcon: "ph-bold ph-hard-drives",
    tagLabel: "Advisory",
    slideClass: "cs-4",
    title: "System Maintenance",
    shortDesc:
      "Portal and dev servers will undergo scheduled maintenance this weekend.",
    fullDesc:
      "Scheduled maintenance will affect the Employee Portal, development servers, and internal APIs this weekend (March 15\u201316). Expected downtime is 4 hours starting at 10:00 PM PHT Saturday. All critical services will have failover systems active. Please save your work and plan accordingly.",
    date: "March 15, 2026",
    location: "Infrastructure",
    posterGradient: "linear-gradient(135deg, var(--inspire-green), #064e3b)",
  },
];

export const departmentData: DepartmentData[] = [
  {
    id: "customer",
    name: "Customer Care Department",
    icon: "ph-duotone ph-headset",
    color: "#06b6d4",
    rgb: "6,182,212",
    desc: "Customer service, support, and relationship management.",
    tags: ["Support", "Relations", "Service", "Retention"],
    videos: [
      { title: "Customer Support Process", desc: "End-to-end guide for handling customer inquiries.", duration: "9:15" },
      { title: "Escalation Procedures", desc: "How to escalate and resolve complex customer issues.", duration: "7:30" },
      { title: "CRM System Overview", desc: "Managing customer records and interaction history.", duration: "8:50" },
    ],
    docs: [
      { title: "Customer Service Handbook", desc: "Standards and procedures for customer-facing staff.", size: "2.2 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Escalation Matrix", desc: "Contact hierarchy for issue escalation.", size: "0.6 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Customer Satisfaction Report", desc: "Monthly CSAT scores and feedback summary.", size: "1.0 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
    ],
    team: [
      { name: "Grace Villanueva", role: "Customer Relations Head", initials: "GV", head: true },
      { name: "Leo Pascual", role: "Senior Support Specialist", initials: "LP" },
      { name: "Mia Torres", role: "Customer Experience Officer", initials: "MT" },
      { name: "Dan Flores", role: "Support Coordinator", initials: "DF" },
    ],
  },
  {
    id: "corporate",
    name: "Corporate Department",
    icon: "ph-duotone ph-briefcase",
    color: "#8b5cf6",
    rgb: "139,92,246",
    desc: "Corporate governance, strategy, stakeholder relations, and compliance.",
    tags: ["Governance", "Strategy", "Compliance", "Stakeholders"],
    videos: [
      { title: "Corporate Governance Overview", desc: "Structure, policies, and decision-making framework.", duration: "12:10" },
      { title: "Stakeholder Communication", desc: "Guidelines for investor and partner communications.", duration: "9:35" },
      { title: "Strategic Planning Process", desc: "Annual strategy cycle and department alignment.", duration: "11:50" },
    ],
    docs: [
      { title: "Corporate Policy Manual", desc: "Company-wide policies and governance guidelines.", size: "3.5 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Strategic Plan 2026–2028", desc: "Three-year strategic roadmap and objectives.", size: "4.5 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Board Meeting Minutes", desc: "Latest board meeting summary and action items.", size: "1.3 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
    ],
    team: [
      { name: "James Whitfield", role: "Chief Executive Officer", initials: "JW", head: true },
      { name: "Maria Santos", role: "Chief Operating Officer", initials: "MS" },
      { name: "Richard Tan", role: "Chief Financial Officer", initials: "RT" },
      { name: "Elena Cruz", role: "Executive Assistant", initials: "EC" },
    ],
  },
  {
    id: "admin",
    name: "Admin Department",
    icon: "ph-duotone ph-buildings",
    color: "#10b981",
    rgb: "16,185,129",
    desc: "Facilities management, logistics, procurement, and office operations.",
    tags: ["Facilities", "Logistics", "Procurement", "Operations"],
    videos: [
      { title: "Facility Booking System", desc: "How to reserve meeting rooms and event spaces.", duration: "5:30" },
      { title: "Fleet Management Overview", desc: "Vehicle request and tracking procedures.", duration: "8:45" },
      { title: "Supply Chain Process", desc: "End-to-end procurement workflow.", duration: "11:20" },
    ],
    docs: [
      { title: "Facility Usage Guidelines", desc: "Rules and schedules for shared company spaces.", size: "1.8 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Vehicle Request Form", desc: "Standard form for company vehicle booking.", size: "0.5 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Vendor Contact Directory", desc: "Approved vendor list with contact information.", size: "1.1 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
    ],
    team: [
      { name: "Patricia Lim", role: "Admin Director", initials: "PL", head: true },
      { name: "Marco Reyes", role: "Facilities Manager", initials: "MR" },
      { name: "Diana Cruz", role: "Logistics Coordinator", initials: "DC" },
      { name: "Kevin Ong", role: "Fleet Supervisor", initials: "KO" },
    ],
  },
  {
    id: "it",
    name: "IT Department",
    icon: "ph-duotone ph-cpu",
    color: "#2563eb",
    rgb: "37,99,235",
    desc: "Infrastructure, development, and tech support for the entire organization.",
    tags: ["Infrastructure", "DevOps", "Security", "Support"],
    videos: [
      { title: "Network Setup Guide", desc: "Configure VPN, proxy settings, and internal DNS for secure access.", duration: "12:34" },
      { title: "Workstation Imaging SOP", desc: "Standard operating procedure for deploying new machines.", duration: "8:21" },
      { title: "Incident Response Protocol", desc: "Step-by-step guide for handling security incidents.", duration: "15:07" },
    ],
    docs: [
      { title: "IT Security Policy 2026", desc: "Updated security guidelines and compliance requirements.", size: "2.4 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Network Architecture Map", desc: "Complete topology of internal and external networks.", size: "5.1 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Software Inventory List", desc: "Licensed software and version tracking sheet.", size: "1.8 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
    ],
    team: [
      { name: "Marcus Chen", role: "IT Director", initials: "MC", head: true },
      { name: "Sarah Kim", role: "Senior Developer", initials: "SK" },
      { name: "Jake Torres", role: "System Administrator", initials: "JT" },
      { name: "Amy Reyes", role: "Network Engineer", initials: "AR" },
      { name: "David Park", role: "Help Desk Lead", initials: "DP" },
    ],
    repos: [
      { name: "inspire-portal", desc: "Main employee portal frontend and API. Next.js + Tailwind.", envs: ["prod", "staging"], url: "https://github.com/inspiregroup/inspire-portal" },
      { name: "iwallet-api", desc: "Payment processing microservice with multi-currency support.", envs: ["prod", "staging"], url: "https://github.com/inspiregroup/iwallet-api" },
      { name: "infra-scripts", desc: "Ansible playbooks and Terraform configs for server provisioning.", envs: ["prod"], url: "https://github.com/inspiregroup/infra-scripts" },
      { name: "ai-toolkit", desc: "AI assistant configuration and prompt files for automated dev support.", envs: ["prod"], url: "https://github.com/inspiregroup/ai-toolkit" },
    ],
    envFiles: [
      { name: ".env.production.txt", desc: "Production environment variables for the portal and API services.", size: "3 KB" },
      { name: ".env.staging.txt", desc: "Staging environment variables — mirrors production with test credentials.", size: "3 KB" },
      { name: ".env.infra.txt", desc: "Infrastructure secrets for Terraform and Ansible provisioning scripts.", size: "2 KB" },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate Department",
    icon: "ph-duotone ph-house-line",
    color: "#14b8a6",
    rgb: "20,184,166",
    desc: "Property acquisition, leasing, portfolio management, and site development.",
    tags: ["Property", "Leasing", "Acquisitions", "Development"],
    videos: [
      { title: "Property Acquisition Process", desc: "Steps for evaluating and acquiring new properties.", duration: "11:30" },
      { title: "Lease Management Guide", desc: "How to manage active lease agreements and renewals.", duration: "8:15" },
      { title: "Site Development Overview", desc: "Planning and execution of property development projects.", duration: "13:45" },
    ],
    docs: [
      { title: "Property Portfolio Report", desc: "Current inventory of owned and leased properties.", size: "3.2 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Lease Agreement Template", desc: "Standard lease contract for commercial properties.", size: "1.6 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Site Valuation Tracker", desc: "Market value tracking for all active properties.", size: "1.0 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
    ],
    team: [
      { name: "Angela Soriano", role: "Real Estate Director", initials: "AS", head: true },
      { name: "Marco Villanueva", role: "Property Manager", initials: "MV" },
      { name: "Claire Tan", role: "Leasing Officer", initials: "CT" },
      { name: "Ben Santos", role: "Site Development Analyst", initials: "BS" },
    ],
  },
  {
    id: "iwallet",
    name: "Iwallet Department",
    icon: "ph-duotone ph-wallet",
    color: "#f97316",
    rgb: "249,115,22",
    desc: "Digital wallet operations, payment processing, and financial product support.",
    tags: ["Payments", "Digital Wallet", "Finance", "Support"],
    videos: [
      { title: "Iwallet Product Overview", desc: "Full walkthrough of Iwallet features and use cases.", duration: "9:20" },
      { title: "Transaction Dispute Handling", desc: "How to process and resolve payment disputes.", duration: "7:40" },
      { title: "Wallet Onboarding Flow", desc: "Step-by-step user onboarding for new wallet accounts.", duration: "6:55" },
    ],
    docs: [
      { title: "Iwallet Operations Manual", desc: "Day-to-day procedures for wallet operations team.", size: "2.5 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Payment Reconciliation Guide", desc: "How to reconcile daily transaction records.", size: "1.3 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "KYC Compliance Checklist", desc: "Know-Your-Customer verification requirements.", size: "0.9 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
    ],
    team: [
      { name: "Nathan Lim", role: "Iwallet Operations Head", initials: "NL", head: true },
      { name: "Paula Reyes", role: "Payment Specialist", initials: "PR" },
      { name: "Sam Cruz", role: "Compliance Officer", initials: "SC" },
      { name: "Tina Go", role: "Customer Support Lead", initials: "TG" },
    ],
    repos: [
      { name: "iwallet-api", desc: "Core payment processing API with multi-currency and transfer support.", envs: ["prod", "staging"], url: "https://github.com/inspiregroup/iwallet-api" },
      { name: "iwallet-web", desc: "Iwallet web dashboard for account management and transaction history.", envs: ["prod", "staging"], url: "https://github.com/inspiregroup/iwallet-web" },
      { name: "kyc-service", desc: "Know-Your-Customer verification microservice and compliance engine.", envs: ["prod"], url: "https://github.com/inspiregroup/kyc-service" },
      { name: "wallet-reconciler", desc: "Automated daily reconciliation and settlement reporting tool.", envs: ["prod"], url: "https://github.com/inspiregroup/wallet-reconciler" },
    ],
    envFiles: [
      { name: ".env.iwallet-api.txt", desc: "API keys, database credentials, and payment gateway secrets for iwallet-api.", size: "4 KB" },
      { name: ".env.iwallet-web.txt", desc: "Frontend environment config including API base URL and feature flags.", size: "2 KB" },
      { name: ".env.kyc-service.txt", desc: "KYC provider credentials and verification service endpoints.", size: "2 KB" },
    ],
  },
  {
    id: "solution",
    name: "Solution Department",
    icon: "ph-duotone ph-lightbulb",
    color: "#0ea5e9",
    rgb: "14,165,233",
    desc: "Business solutions, consulting, and technology-driven innovation services.",
    tags: ["Consulting", "Innovation", "Solutions", "Strategy"],
    videos: [
      { title: "Solution Design Framework", desc: "How we scope, design, and deliver business solutions.", duration: "10:20" },
      { title: "Client Discovery Process", desc: "Techniques for uncovering client needs and pain points.", duration: "8:05" },
      { title: "Implementation Methodology", desc: "End-to-end delivery approach for solution projects.", duration: "12:15" },
    ],
    docs: [
      { title: "Solutions Catalog 2026", desc: "Overview of all available business and tech solutions.", size: "3.1 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Project Proposal Template", desc: "Standard template for client solution proposals.", size: "1.2 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "ROI Assessment Tool", desc: "Spreadsheet for calculating solution return on investment.", size: "0.9 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
    ],
    team: [
      { name: "Claire Mendoza", role: "Solutions Director", initials: "CM", head: true },
      { name: "Nico Ramos", role: "Senior Solutions Consultant", initials: "NR" },
      { name: "Bea Castillo", role: "Business Analyst", initials: "BC" },
      { name: "Jeff Ocampo", role: "Implementation Specialist", initials: "JO" },
    ],
  },
  {
    id: "jba",
    name: "Joint Business Venture",
    icon: "ph-duotone ph-handshake",
    color: "#d946ef",
    rgb: "217,70,239",
    desc: "Strategic partnerships, joint ventures, and collaborative business initiatives.",
    tags: ["Partnerships", "Joint Ventures", "Collaboration", "Business Dev"],
    videos: [
      { title: "JBA Partnership Framework", desc: "How Inspire Group structures joint business agreements.", duration: "11:00" },
      { title: "Due Diligence Process", desc: "Steps for evaluating potential joint venture partners.", duration: "9:45" },
      { title: "Revenue Sharing Models", desc: "Overview of partnership revenue and profit sharing.", duration: "8:20" },
    ],
    docs: [
      { title: "JBA Partnership Agreement", desc: "Standard template for joint business arrangement contracts.", size: "2.8 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Partner Evaluation Criteria", desc: "Scoring framework for assessing partnership candidates.", size: "1.1 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Active Partnerships Tracker", desc: "Current JBA portfolio with status and revenue data.", size: "1.4 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
    ],
    team: [
      { name: "Sophia Lim", role: "JBA Head", initials: "SL", head: true },
      { name: "Carlos Vega", role: "Partnership Manager", initials: "CV" },
      { name: "Anna Reyes", role: "Business Development Officer", initials: "AR" },
      { name: "Tim Uy", role: "Legal & Compliance Liaison", initials: "TU" },
    ],
  },
  {
    id: "marketing",
    name: "Marketing Department",
    icon: "ph-duotone ph-megaphone",
    color: "#ef4444",
    rgb: "239,68,68",
    desc: "Brand management, digital marketing, campaigns, and communications.",
    tags: ["Branding", "Campaigns", "Digital", "Communications"],
    videos: [
      { title: "Brand Guidelines Overview", desc: "Logo usage, color palette, and tone-of-voice standards.", duration: "7:45" },
      { title: "Campaign Planning Process", desc: "How to plan and execute a marketing campaign.", duration: "10:30" },
      { title: "Social Media Strategy", desc: "Content calendar, posting schedule, and engagement tips.", duration: "8:15" },
    ],
    docs: [
      { title: "Brand Identity Guide", desc: "Complete brand standards for all visual and written output.", size: "4.2 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Marketing Calendar 2026", desc: "Annual campaign schedule and key marketing dates.", size: "1.0 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
      { title: "Media Kit", desc: "Press assets, company overview, and product briefs.", size: "6.5 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
    ],
    team: [
      { name: "Isabella Cruz", role: "Marketing Director", initials: "IC", head: true },
      { name: "Ryan Lee", role: "Digital Marketing Specialist", initials: "RL" },
      { name: "Kim Santos", role: "Content & Social Media Manager", initials: "KS" },
      { name: "Marc Dela Rosa", role: "Graphic Designer", initials: "MD" },
    ],
  },
  {
    id: "utility",
    name: "Consultant",
    icon: "ph-duotone ph-wrench",
    color: "#f59e0b",
    rgb: "245,158,11",
    desc: "Consulting services, strategic planning, and cross-functional advisory support.",
    tags: ["Consulting", "Strategy", "Advisory", "Support"],
    videos: [
      { title: "Preventive Maintenance Schedule", desc: "Overview of monthly and quarterly maintenance tasks.", duration: "6:50" },
      { title: "Utilities Monitoring Guide", desc: "How to track and report electricity, water, and HVAC usage.", duration: "5:40" },
      { title: "Work Order System Tutorial", desc: "Submitting and managing maintenance work orders.", duration: "4:55" },
    ],
    docs: [
      { title: "Maintenance SOP Manual", desc: "Standard procedures for all maintenance activities.", size: "2.1 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
      { title: "Utilities Consumption Report", desc: "Monthly utility usage and cost breakdown.", size: "0.9 MB", type: "XLSX", icon: "ph-duotone ph-file-xls" },
      { title: "Emergency Response Guide", desc: "Protocols for power outages and facility emergencies.", size: "1.0 MB", type: "PDF", icon: "ph-duotone ph-file-pdf" },
    ],
    team: [
      { name: "Edgar Ramos", role: "Consulting Supervisor", initials: "ER", head: true },
      { name: "Joel Bautista", role: "Electrician", initials: "JB" },
      { name: "Rene Aguilar", role: "Plumber & HVAC Tech", initials: "RA" },
      { name: "Luz Hernandez", role: "Facilities Support", initials: "LH" },
    ],
  },
];
